Default: &defaults
  user: hobby-site3
  password: hobby-site3
  host: localhost
  port: 5432
  database: hobby-site3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: hobby-site3_test
  <<: *defaults

Staging:
  database: hobby-site3_staging
  poolsize: 100
  <<: *defaults

Production:
  database: hobby-site3_production
  poolsize: 100
  <<: *defaults
